workdir: "data4"
# options are ["nuc", "prot"]
chartype: "nuc"


apples_config:
  # [FM, OLS]
  method: FM
  # float. 0-infinity
  filter: 0.25
  # integer. 5-infinity
  base: 25

prep_config:
  # cluster must have a minimum diameter
  edge_thr: 0.02
  # approximate cluster size (no guarantees)
  cluster_size: 50
  # cores used in preperation tasks such as decompose and prep_backbone_alignments
  cores: 4
  # minimum alignment overlap
  overlap: 50

infer_config:
  # [raxml-ng,iqtree,raxml-8]
  method: "raxml-8"
  # number of starting trees
  numstart: 2


